name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: ap-southeast-1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        pytest test_app.py -v

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      env:
        FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        envs: FLASK_SECRET_KEY
        script: |
          echo "Deploying at $(date -u '+%Y-%m-%d %H:%M:%S')"
          
          cd ~/task-tracker || git clone https://github.com/min-hit-1701/task-tracker.git ~/task-tracker
          cd ~/task-tracker
          git fetch
          git reset --hard origin/main
          
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo usermod -aG docker $USER
          
          # Ensure data persistence
          docker volume create task-tracker-data
          
          # Stop and remove existing container
          docker stop task-tracker || true
          docker rm task-tracker || true
          
          # Build new image
          docker build -t task-tracker .
          
          # Run with proper permissions and environment
          docker run -d \
            --name task-tracker \
            -p 8080:8080 \
            -v task-tracker-data:/app/instance \
            -e SECRET_KEY="${FLASK_SECRET_KEY}" \
            -e FLASK_ENV=production \
            -e PYTHONUNBUFFERED=1 \
            --restart unless-stopped \
            task-tracker
          
          # Wait for container to start and check logs
          sleep 5
          docker logs task-tracker
          
          echo "Deployment completed at $(date -u '+%Y-%m-%d %H:%M:%S')"